# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClassQuest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClassQuest
   pod 'GoogleSignIn'
   pod 'Firebase/Core'
   pod 'SnapSDK' 
 target 'ClassQuestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClassQuestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
